### ISSUE TITLE
random tests fail occasionally

### ISSUE THREAD

**Issue by samth** [racket/htdp#132]
Some of the randomized tests in `tests/test-engine/racket-tests` fail occasionally. See http://drdr.racket-lang.org/56554/racket/share/pkgs/htdp-test/tests/test-engine/racket-tests.rkt for an example. 

The relevant failing tests are: 
- https://github.com/racket/htdp/blob/master/htdp-test/tests/test-engine/racket-tests.rkt#L229-L233
- https://github.com/racket/htdp/blob/master/htdp-test/tests/test-engine/racket-tests.rkt#L240-L241

I'm not certain what the specification being tested here is, or I would propose a fix.

The code was originally added in https://github.com/racket/htdp/commit/26e36b6dade7d6c7c95ea1c019e4a7808c82a8ed and may actually be by @dvanhorn.

**Comment by mfelleisen** [comment]
DVH suggested this addition, with sketches of tests. I implemented them and left DVH’s suggestion in as comments. It is safe to comment them out (so they stay as an acknowledgement of his inspiration).

**Comment by dvanhorn** [comment]
I believe the idea was that `check-random` sets up the rng seed so that a
sequence of calls to `random` in the checked expression will be the same as
a sequence of calls in the expected expressions (assuming the same
arguments).

It looks like these tests which have different sequences of calls (and
therefore intended to fail) are occasionally getting (un)lucky and
producing the same results.

I think it would be fine to comment out, or you could make the sequence
longer so that this kind of coincidence is astronomically unlikely (and we
should buy lottery tickets when the tests fail).

David

**Comment by samth** [comment]
I like the idea of adding more checks, that should fix the problem nicely, especially if the numbers are larger.
