### ISSUE TITLE
Bad error message for foldl

### ISSUE THREAD

**Issue by florence** [racket/htdp#14]
`foldl`'s error report all of its arguments one position off.

```
> (foldl + 0  5)
foldl : 2th argument must be a list, given 5
```

but `5` is the 3rd argument.

**Comment by rprimus** [comment]
Wed Nov 11 21:30:24 GMT 2015

1.  When reporting errors,  it is always Good Thing (tm) to include:
    a.  What version of software you are running
    b.  What OS

If not running the latest,  the first thing (most likely) you'll be suggested to do is install the latest.

The output I get is:

```racket
Welcome to Racket v6.2.1.
-> (require lang/htdp-advanced)
-> (foldl + 0 5)
; foldl : third argument must be a list, given 5 [,bt for context]
```

The correct form should be ```(foldl + 0 '(5))```

This was fixed in commit: 4ad805c4f1e7daa5ae8fdc457c7c2cd1ab134b4d.
