### ISSUE TITLE
clarify error message for nested defines

### ISSUE THREAD

**Issue by bennn** [racket/htdp#28]
#### Inspiration:
[https://groups.google.com/d/msg/racket-users/j9Gri7M6i9E/LggwDfveCwAJ]()

#### TLDR:
1. Programmer `A` posted BSL-like code that used `>` as an infix operator, got confused by the error message
2. Programmer `B` suggested trying BSL because BSL gives much better error messages for that sort of thing
3. Programmer `A` pasted his code into a BSL window. The code happened to use a nested helper function. Programmer `A` saw the error message "define: expected only one expression for the function body but found 1 extra part" and got confused.

#### Proposal:
Given code like
```
(define (f x)
  (define y (+ x 1))
  y)
```
- BSL should say something like "nested definitions not supported"
- ISL should mention `local`

**Comment by maueroats** [comment]
First of all, for clarity: none of the Student Languages allow multiple expressions in the body of a function. For example, the same error message is generated by the `g` function below. This error occurs before any examination of the body of the function.
```
(define (g y)
  (+ y 10)
  (* 2 y))
```
In this case, ASL could mention `begin` but does not.

Second, if there is interest in this issue, I think it would be relatively easy to add a message for this particular error case, when the define is the first item in the function body, by inserting a check right before [the check that there is no more than one expression in the function body](https://github.com/racket/htdp/blob/be525ec6c6ad37904f6895b2b427fb73c04e6c46/htdp-lib/lang/private/teach.rkt#L641).

This would not solve the general problem of `define` appearing anywhere in the body (probably), so perhaps it is not worth implementing.

I don't know what I think about this. Having more than one thing in side a function in a student language is a pretty big error, so perhaps signalling that is enough.

I can submit a PR if the approach outlined above is desirable.

**Comment by mfelleisen** [comment]
The error-message philosophy of *SL is to _explain_ the error as well as possible but not suggest fixes .. because these suggestions are often plain wrong. This issue has been subjected to extensive research by Guillaume Marceau, Kathi Fisler, and Shriram Krishnamurthi. We carefully changed the error message to be consistent and use vocabulary consistent with what students seem to recognize. 

Because *SL languages are usually used, students who make such mistakes should seek advice from TAs instead because they clearly suffer from deeper problems than just missing a paren or so. 

Take a look at @maueroats 's example. Since the first expression is effect-free, perhaps the student meant 

```
(define (g y) 
  (if (something y) 
      (+ y 10) 
      (* 2 y)))
```

Who's to say? 

And similarly @bennn 's example could also be a problem with `define` vs something completely different. Making suggestions is the wrong thing in *SL.

**Comment by mfelleisen** [comment]
@maueroats But thanks for your offer to create a PR.
