### ISSUE TITLE
No highlighting when struct accessors crash

### ISSUE THREAD

**Issue by dvanhorn** [racket/htdp#42]
Misusing user-defined structure accessors does not highlight any expression in red when a crash occurs:
```
(define-struct s (x))
(s-x '())
```
This makes tracking down errors in larger programs really difficult for students.

Note that this is not a problem for built-in structures; this highlights the relevant expression:
```
(posn-x '())
```

**Comment by michaelballantyne** [comment]
This appears to be because DrRacket applies errortrace annotation to the code introduced by the define-struct macro. The invocation of `raw` [here](https://github.com/racket/htdp/blob/0e80d945603ec345e7a78cdb56d60b0d68adf104/htdp-lib/lang/private/teach.rkt#L1002) gets a with-continuation-mark wrapper that overwrites the continuation mark attached to the call of `(s-x '())`.

The "right" solution is probably to stop DrRacket from doing that; see racket/drracket#157. The easy fix is to remove the eta-expansion of `raw`, as in https://github.com/racket/htdp/pull/43.

There's a further issue here, which is that whatever magic DrRacket does to highlight the original expression that caused an error even when it doesn't have an errortrace continuation mark doesn't seem to work for the teaching languages. For example, this program in Racket:

```
#lang racket
(define (f x)
  (error 'bad "bad"))
(f 5)
```

highlights the invocation of error but also draws an arrow to the call `(f 5)`, despite `(f 5)` the fact that the continuation mark for `(f 5)` is overwritten because it is a tail call. The same program in Beginning Student does not draw the arrow.

This may be related to the extra errortrace continuation mark applied to the code introduced by module begin to print the result of top-level expressions. In #lang racket that code doesn't get errortrace annotations, but for some reason it does in the teaching languages. I don't know how to track that one down.

**Comment by mfelleisen** [comment]
Language tests passed.
